<script setup lang="ts">
import { computed,ref,watch } from 'vue'
import { useRoute } from 'vue-router'
import { dashboardService } from '@/services/dashboard'
import { problemMessage } from '@/api/client'
import type { InspectionDetail,HydrantInspectionHistoryItem } from '@/api/types'
import { compareInspections } from './inspection-compare'
import PrivateThumbnail from '@/features/photos/PrivateThumbnail.vue'
const route=useRoute(),left=ref<InspectionDetail>(),right=ref<InspectionDetail>(),options=ref<HydrantInspectionHistoryItem[]>([]),selected=ref(''),error=ref(''),loading=ref(false),onlyChanges=ref(true)
let generation=0
const rows=computed(()=>left.value&&right.value?compareInspections(left.value,right.value).filter(x=>!onlyChanges.value||x.changed||x.definitionChanged):[])
async function load(){const id=++generation;loading.value=true;error.value='';right.value=undefined;try{const a=await dashboardService.inspection(String(route.params.id));const first=await dashboardService.hydrantInspections(a.hydrantId,1,100);let all=first.items;for(let page=2;page<=Math.ceil(first.total/100);page++){if(id!==generation)return;all=all.concat((await dashboardService.hydrantInspections(a.hydrantId,page,100)).items)}if(id!==generation)return;left.value=a;options.value=all.filter(x=>x.inspectionId!==a.inspectionId)}catch(e){error.value=problemMessage(e,'No se pudo cargar el historial.')}finally{if(id===generation)loading.value=false}}
async function compare(){const id=++generation;error.value='';loading.value=true;right.value=undefined;try{const b=await dashboardService.inspection(selected.value);if(id!==generation)return;if(b.hydrantId!==left.value?.hydrantId)throw new Error('Distinto hidrante');right.value=b}catch(e){error.value=problemMessage(e,'No se pudo comparar la revisión.')}finally{if(id===generation)loading.value=false}}
watch(()=>route.params.id,load,{immediate:true})
</script>
<template><div class="content comparison"><RouterLink :to="`/revisiones/${route.params.id}`">Volver al expediente</RouterLink><h1>Comparar revisiones</h1><p v-if="error" role="alert">{{ error }}</p><p v-if="loading">Cargando…</p><template v-if="left"><p>Hidrante {{ left.accountNumber }} · Revisión base #{{ left.revisionNumber }} · Checklist {{ left.checklistCode }} v{{ left.checklistVersion }}</p><form @submit.prevent="compare"><label>Comparar con<select v-model="selected" required><option value="">Selecciona una revisión</option><option v-for="x in options" :key="x.inspectionId" :value="x.inspectionId">#{{ x.revisionNumber }} · {{ new Date(x.startedAt).toLocaleDateString('es-MX') }} · {{ x.technicianName }}</option></select></label><button class="btn" :disabled="loading||!selected">Comparar</button></form><p v-if="!options.length&&!loading">No hay otra revisión disponible para comparar.</p></template><template v-if="right&&left"><p>Comparada: #{{ right.revisionNumber }} · Checklist {{ right.checklistCode }} v{{ right.checklistVersion }}</p><p v-if="left.status==='inactive'||right.status==='inactive'">La revisión Ausente no requiere respuestas del checklist ordinario.</p><label><input v-model="onlyChanges" type="checkbox" />Sólo diferencias</label><div class="table-wrap card"><table><thead><tr><th>Pregunta</th><th>Base</th><th>Comparada</th></tr></thead><tbody><tr v-for="r in rows" :key="r.code"><td>{{ r.label }} <small>{{ r.code }}{{ r.definitionChanged?' · Definición modificada':'' }}</small></td><td>{{ r.left }}</td><td>{{ r.right }}</td></tr></tbody></table><p v-if="!rows.length">Sin diferencias en respuestas para este filtro.</p></div><div class="evidence"><section v-for="d in [left,right]" :key="d.inspectionId" class="card"><h2>Evidencia #{{ d.revisionNumber }}</h2><RouterLink :to="`/revisiones/${d.inspectionId}?foto=${d.photos[0]?.photoId||''}`">Abrir visor de originales</RouterLink><div v-for="p in d.photos" :key="p.photoId"><p>{{ p.slotLabel||p.slotCode }}</p><PrivateThumbnail :photo="{...p,inspectionId:d.inspectionId,hydrantId:d.hydrantId,accountNumber:d.accountNumber,revisionNumber:d.revisionNumber,technicianName:d.technicianName}" :status-label="p.uploadStatus" /></div></section></div></template></div></template>
<style scoped>.comparison{display:grid;gap:14px}form{display:flex;gap:12px;align-items:end;flex-wrap:wrap}label{display:grid;gap:6px}select{padding:8px;max-width:100%}.table-wrap{overflow:auto}table{width:100%;border-collapse:collapse}td,th{padding:12px;border-bottom:1px solid var(--line);text-align:left}small{display:block}.evidence{display:grid;grid-template-columns:1fr 1fr;gap:14px}.evidence section{padding:15px;min-width:0}@media(max-width:650px){.evidence{grid-template-columns:1fr}}</style>
