<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import type { EChartsCoreOption } from 'echarts/core'
import { Camera, ClipboardCheck, Droplets, Gauge } from '@lucide/vue'
import EChart from '@/components/EChart.vue'
import { dashboardService } from '@/services/dashboard'
import { problemMessage } from '@/api/client'
import type { DashboardSummary } from '@/api/types'

const data=ref<DashboardSummary>(),loading=ref(true),error=ref('')
const statusLabels:Record<string,string>={draft:'Borrador',in_progress:'En progreso',pending_sync:'Pendiente sync',submitted:'Enviada',validated:'Validada',rejected:'Rechazada',cancelled:'Cancelada'}
onMounted(async()=>{try{data.value=await dashboardService.summary()}catch(e){error.value=problemMessage(e,'No fue posible cargar el dashboard.')}finally{loading.value=false}})
const lineOption=computed<EChartsCoreOption>(()=>({tooltip:{trigger:'axis'},grid:{left:38,right:18,top:20,bottom:30},xAxis:{type:'category',data:data.value?.activity.map(x=>x.date.slice(5))||[],axisLine:{lineStyle:{color:'#d7e0ea'}}},yAxis:{type:'value',splitLine:{lineStyle:{color:'#edf1f5'}}},series:[{type:'line',smooth:true,data:data.value?.activity.map(x=>x.count)||[],lineStyle:{color:'#1768f5',width:3},itemStyle:{color:'#1768f5'},areaStyle:{color:'#e9f1ff'}}]}))
const donutOption=computed<EChartsCoreOption>(()=>({tooltip:{trigger:'item'},legend:{bottom:0},series:[{type:'pie',radius:['48%','72%'],center:['50%','43%'],label:{show:false},data:data.value?.byStatus.map(x=>({name:statusLabels[x.status]||x.status,value:x.count}))||[]}]}))
</script>
<template><div class="content"><div class="page-head"><div><h1 class="page-title">Dashboard</h1><p class="page-subtitle">Supervisión general — datos operativos reales</p></div><span class="muted desktop-only">Actualización al cargar</span></div><div v-if="loading" class="metric-grid"><div v-for="n in 4" :key="n" class="card skeleton metric"/></div><div v-else-if="error" class="error-box" role="alert">{{error}}</div><template v-else-if="data"><section aria-labelledby="advance"><h2 id="advance" class="section-label">AVANCE GENERAL</h2><div class="metric-grid"><RouterLink class="card metric metric-link" to="/hidrantes"><Droplets/><small>HIDRANTES TOTALES</small><strong>{{data.totalHydrants.toLocaleString()}}</strong><span>Universo activo</span></RouterLink><RouterLink class="card metric metric--blue metric-link" :to="{path:'/hidrantes',query:{reviewed:'true'}}"><ClipboardCheck/><small>HIDRANTES REVISADOS</small><strong>{{data.reviewedHydrants.toLocaleString()}}</strong><span>Con revisión recibida</span></RouterLink><RouterLink class="card metric metric-link" :to="{path:'/hidrantes',query:{reviewed:'false'}}"><Gauge/><small>PENDIENTES</small><strong>{{data.pendingHydrants.toLocaleString()}}</strong><span>Sin revisión recibida</span></RouterLink><article class="card metric metric--green"><Camera/><small>AVANCE GENERAL</small><strong>{{data.progressPercent}}%</strong><div class="progress"><i :style="{width:`${data.progressPercent}%`}"/></div></article></div></section><section><h2 class="section-label">REVISIONES</h2><div class="mini-grid"><article class="card"><small>Total</small><b>{{data.totalInspections}}</b></article><article class="card"><small>Hoy</small><b>{{data.inspectionsToday}}</b></article><article v-for="s in data.byStatus" :key="s.status" class="card"><small>{{statusLabels[s.status]||s.status}}</small><b>{{s.count}}</b></article></div></section><div class="charts"><article class="card chart-card"><header><b>Actividad de revisiones</b><small>Últimos 30 días</small></header><EChart :option="lineOption"/></article><article class="card chart-card"><header><b>Estado de revisiones</b><small>Distribución real</small></header><EChart :option="donutOption"/></article><article class="card tech"><header><b>Revisiones por técnico</b><small>Acumulado</small></header><ol><li v-for="x in data.byTechnician" :key="x.userId"><span>{{x.name}}</span><i :style="{width:`${Math.max(5,x.count/(data.byTechnician[0]?.count||1)*100)}%`}"/><b>{{x.count}}</b></li></ol></article><article class="card photos"><Camera/><div><small>FOTOGRAFÍAS VERIFICADAS</small><strong>{{data.verifiedPhotos.toLocaleString()}}</strong></div></article></div></template></div></template>
<style scoped>.metric-link{text-decoration:none;color:inherit}.section-label{font-size:.75rem;color:#60748f;margin:22px 0 10px}.metric-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:12px}.metric{min-height:118px;padding:17px;display:grid;grid-template-columns:1fr auto;align-items:center}.metric svg{grid-column:2;color:#8da0b7}.metric small,.metric strong,.metric span,.progress{grid-column:1/-1}.metric small{color:#59708c}.metric strong{font:700 1.65rem ui-monospace,monospace}.metric span{font-size:.77rem;color:#8294ac}.metric--blue strong{color:#165ce9}.metric--green strong{color:#0c9c4b}.progress{height:6px;background:#edf1f5;border-radius:9px;overflow:hidden}.progress i{display:block;height:100%;background:#12a153}.mini-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(115px,1fr));gap:9px}.mini-grid article{text-align:center;padding:12px;display:grid;gap:4px}.mini-grid small{color:#647a95}.mini-grid b{font:700 1.15rem ui-monospace,monospace}.charts{display:grid;grid-template-columns:2fr 1fr;gap:14px;margin-top:20px}.chart-card{padding:16px;height:330px}.chart-card header,.tech header{display:grid}.chart-card header small,.tech header small{color:#8294ab;font-size:.72rem}.tech{padding:17px}.tech ol{padding:0;list-style:none}.tech li{display:grid;grid-template-columns:130px 1fr 30px;gap:10px;align-items:center;font-size:.8rem;margin:13px 0}.tech li i{height:6px;background:#2870f5;border-radius:4px}.photos{display:flex;align-items:center;justify-content:center;gap:18px;padding:25px;color:#1763eb}.photos div{display:grid}.photos strong{font:700 2rem ui-monospace,monospace}.photos small{color:#667b96}@media(max-width:1100px){.metric-grid{grid-template-columns:repeat(2,1fr)}.charts{grid-template-columns:1fr}}@media(max-width:560px){.metric-grid{grid-template-columns:1fr 1fr}.metric{min-height:105px;padding:13px}.metric strong{font-size:1.3rem}.charts{display:block}.chart-card,.tech,.photos{margin-bottom:12px}.mini-grid{grid-template-columns:repeat(2,1fr)}}</style>
