import { api } from '@/api/client'
import type { ConstructionDataSource } from './construction.datasource'
import { constructionStepNames, type ConstructionHistoryEntry, type ConstructionPhoto, type ConstructionSurvey } from './construction.types'
type Row=Record<string,unknown>;type Detail={survey:Row;steps:Row[];photos:Row[];corrections:Row[];history:Row[]};type Page={items:Row[]}
const text=(v:unknown,f='')=>v==null?f:String(v), nullable=(v:unknown)=>v==null?null:String(v), num=(v:unknown)=>Number(v??0)
function mapPhoto(r:Row):ConstructionPhoto{const integrity=text(r.integrityStatus);return{id:text(r.photoId),surveyId:text(r.surveyId),stepNumber:r.stepNumber==null?null:num(r.stepNumber),correctionRound:r.correctionRound==null?null:num(r.correctionRound),purpose:nullable(r.purpose) as ConstructionPhoto['purpose'],capturedAt:text(r.capturedAt),location:r.latitude==null?null:{latitude:num(r.latitude),longitude:num(r.longitude),accuracy:num(r.accuracy),altitude:r.altitude==null?null:num(r.altitude)},integrityStatus:integrity==='confirmed'?'confirmed':integrity==='mapping_conflict'?'mapping_conflict':'not_verified',syncState:text(r.storageState)==='verified'?'synchronized':'requires_review'}}
function base(r:Row):ConstructionSurvey{return{id:text(r.surveyId),displayIdentifier:text(r.displayIdentifier),accountNumber:nullable(r.accountNumber),contractorName:text(r.contractorName,'Sin contratista'),contractorUserId:nullable(r.contractorUserId),companyName:nullable(r.crewName),createdAt:text(r.createdAt),updatedAt:text(r.updatedAt),status:text(r.status) as ConstructionSurvey['status'],currentStep:num(r.currentStep),syncState:'synchronized',steps:[],photos:[],corrections:[],history:[],canonicalLocation:r.latitude==null?null:{latitude:num(r.latitude),longitude:num(r.longitude),accuracy:num(r.accuracy)},accountConflict:!!r.accountConflict,conflictingHydrantId:nullable(r.conflictingHydrantId),linkedHydrantId:r.linkedHydrant?nullable(r.conflictingHydrantId):null,alerts:[]}}
function mapDetail(d:Detail){const survey=base(d.survey),photos=d.photos.map(mapPhoto);survey.photos=photos;survey.steps=d.steps.map(r=>({number:num(r.stepNumber),name:text(r.stepName,constructionStepNames[num(r.stepNumber)]),state:text(r.status)==='completed'?'completed':'pending',completedAt:nullable(r.completedAt),comment:nullable(r.comment),photoIds:photos.filter(p=>p.stepNumber===num(r.stepNumber)).map(p=>p.id)}));survey.corrections=d.corrections.map(r=>({id:text(r.correctionId),round:num(r.round),rejectionReason:text(r.rejectionReason),contractorComment:text(r.contractorComment),photoIds:photos.filter(p=>p.correctionRound===num(r.round)).map(p=>p.id),state:text(r.status)==='completed'?'submitted':'pending',createdAt:text(r.createdAt),submittedAt:nullable(r.submittedAt)}));survey.history=d.history.map((r):ConstructionHistoryEntry=>({id:text(r.historyId),fromStatus:nullable(r.fromStatus) as ConstructionHistoryEntry['fromStatus'],toStatus:text(r.toStatus) as ConstructionHistoryEntry['toStatus'],actor:text(r.actor),actorType:(text(r.actorType)==='system'?'admin':text(r.actorType)) as ConstructionHistoryEntry['actorType'],timestamp:text(r.timestamp),reason:nullable(r.reason)}));if(survey.status==='executed')survey.alerts.push({id:'review',kind:'review',label:'Levantamiento pendiente de revisión',severity:'warning'});if(survey.status==='rejected')survey.alerts.push({id:'correction',kind:'correction',label:'Corrección requerida',severity:'danger'});return survey}
export const apiConstructionDataSource:ConstructionDataSource={async list(){return(await api.get<Page>('/admin/dashboard/construction/surveys',{params:{page:1,pageSize:100}})).data.items.map(base)},async getById(id){try{return mapDetail((await api.get<Detail>(`/admin/dashboard/construction/surveys/${id}`)).data)}catch(e:unknown){if((e as{response?:{status?:number}}).response?.status===404)return null;throw e}}}
