import { beforeEach, describe, expect, it, vi } from 'vitest'
const {get,put}=vi.hoisted(()=>({get:vi.fn(),put:vi.fn()}))
vi.mock('@/api/client',()=>({api:{get,put}}))
import { apiConstructionDataSource } from './construction.api.datasource'
import { getConstructionMetrics, getConstructionSummary } from './construction.analytics.service'
import { getConstructionAccess, getConstructionAccessHistory, updateConstructionAccess } from './construction.access.service'

const row={surveyId:'00000000-0000-4000-8000-000000000001',displayIdentifier:'BASE 1',status:'created',currentStep:0,contractorName:'Persona',contractorUserId:'00000000-0000-4000-8000-000000000002',crewId:'00000000-0000-4000-8000-000000000003',crewName:'EMPRESA',createdAt:'2026-09-01T00:00:00Z',updatedAt:'2026-09-01T00:00:00Z'}
describe('Construction API adapters',()=>{beforeEach(()=>vi.clearAllMocks())
 it('sends pagination and every list filter to the server',async()=>{get.mockResolvedValueOnce({data:{items:[row],page:2,pageSize:25,total:30,totalPages:2}});const request={page:2,pageSize:25,search:'base',status:'created' as const,stage:2,contractorId:row.contractorUserId,crewId:row.crewId,from:'2026-08-01T00:00:00Z',to:'2026-09-02T00:00:00Z'};const result=await apiConstructionDataSource.listPage!(request);expect(get).toHaveBeenCalledWith('/admin/dashboard/construction/surveys',{params:request});expect(result.total).toBe(30);expect(result.items[0]?.companyName).toBe('EMPRESA')})
 it('uses summary and metrics endpoints',async()=>{get.mockResolvedValueOnce({data:{total:0}}).mockResolvedValueOnce({data:{status:[],stages:[],temporal:[],contractors:[],companies:[],rejection:{}}});await getConstructionSummary();await getConstructionMetrics();expect(get.mock.calls.map(x=>x[0])).toEqual(['/admin/dashboard/construction/summary','/admin/dashboard/construction/metrics'])})
 it('maps detail photos to protected admin content URLs',async()=>{get.mockResolvedValueOnce({data:{survey:row,steps:[],corrections:[],history:[],photos:[{photoId:'00000000-0000-4000-8000-000000000004',surveyId:row.surveyId,capturedAt:row.createdAt,storageState:'verified'}]}});const detail=await apiConstructionDataSource.getById(row.surveyId);expect(detail?.photos[0]?.thumbnailUrl).toContain('/admin/dashboard/construction/surveys/');expect(detail?.photos[0]?.contentUrl).toContain('/content')})
 it('reads access/history and writes only through PUT confirmation',async()=>{get.mockResolvedValueOnce({data:{userId:'u',constructionRole:'contractor',accessEnabled:true,ownSurveyCount:1}}).mockResolvedValueOnce({data:{items:[]}});await getConstructionAccess('u');await getConstructionAccessHistory('u');await updateConstructionAccess('u','resident');expect(get.mock.calls.map(x=>x[0])).toEqual(['/admin/dashboard/construction/users/u/access','/admin/dashboard/construction/users/u/access-history']);expect(put).toHaveBeenCalledWith('/admin/dashboard/construction/users/u/access',{role:'resident',reason:expect.any(String)})})
})
