<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { useRoute } from 'vue-router'
import { Filter, MapPin, Search, X } from '@lucide/vue'
import AppStatus from '@/components/AppStatus.vue'
import { problemMessage } from '@/api/client'
import type { HydrantFilters, HydrantMasterRecord, Page } from '@/api/types'
import { dashboardService } from '@/services/dashboard'
import { evidenceLabel } from './hydrant-format'

const route=useRoute(),data=ref<Page<HydrantMasterRecord>>(),loading=ref(true),error=ref(''),showFilters=ref(false)
const filters=reactive<HydrantFilters>({page:1,pageSize:25,sort:'accountNumber',direction:'asc',reviewed:route.query.reviewed==='true'?true:route.query.reviewed==='false'?false:undefined})
let debounce:number|undefined
async function load(){loading.value=true;error.value='';const params={...filters,lastFrom:filters.lastFrom?.length===10?`${filters.lastFrom}T00:00:00.000Z`:filters.lastFrom,lastTo:filters.lastTo?.length===10?`${filters.lastTo}T00:00:00.000Z`:filters.lastTo};try{data.value=await dashboardService.hydrants(params)}catch(e){error.value=problemMessage(e,'No fue posible cargar los hidrantes.')}finally{loading.value=false}}
function apply(){filters.page=1;load()}
function search(){window.clearTimeout(debounce);debounce=window.setTimeout(apply,300)}
function clear(){Object.assign(filters,{page:1,pageSize:25,search:undefined,rvStatus:undefined,reviewed:undefined,hasInspections:undefined,installationYear:undefined,flowMin:undefined,flowMax:undefined,outletCount:undefined,coordinates:undefined,lastFrom:undefined,lastTo:undefined,sort:'accountNumber',direction:'asc'});load()}
function go(page:number){if(page<1||!data.value||page>Math.ceil(data.value.total/data.value.pageSize))return;filters.page=page;load()}
const date=(value?:string)=>value?new Intl.DateTimeFormat('es-MX',{dateStyle:'medium',timeZone:'America/Hermosillo'}).format(new Date(value)):'Sin revisión'
onMounted(load)
</script>
<template><div class="content"><div class="page-head"><div><h1 class="page-title">Hidrantes</h1><p class="page-subtitle">Expediente maestro del universo activo</p></div><span v-if="data" class="muted">{{data.total.toLocaleString()}} hidrantes</span></div>
<div class="card toolbar-card"><label class="search"><Search :size="18"/><span class="sr-only">Buscar cuenta</span><input v-model.trim="filters.search" placeholder="Buscar por cuenta" @input="search"/></label><button class="btn" @click="showFilters=!showFilters"><Filter :size="17"/>Filtros</button><button class="btn" aria-label="Limpiar filtros" @click="clear"><X :size="17"/>Limpiar</button></div>
<section v-if="showFilters" class="card filters" aria-label="Filtros de hidrantes"><div class="field"><label>Estado RV</label><select v-model="filters.rvStatus" @change="apply"><option :value="undefined">Todos</option><option value="completed">RV completado</option><option value="pending">Pendiente</option></select></div><div class="field"><label>Revisiones</label><select v-model="filters.hasInspections" @change="apply"><option :value="undefined">Todas</option><option :value="true">Con revisiones</option><option :value="false">Sin revisiones</option></select></div><div class="field"><label>Coordenadas</label><select v-model="filters.coordinates" @change="apply"><option :value="undefined">Todas</option><option value="present">Disponibles</option><option value="absent">Ausentes</option></select></div><div class="field"><label>Año instalación</label><input v-model.number="filters.installationYear" type="number" min="1900" max="2200" @change="apply"/></div><div class="field"><label>Gasto mínimo (L/s)</label><input v-model.number="filters.flowMin" type="number" min="0" step=".1" @change="apply"/></div><div class="field"><label>Salidas</label><input v-model.number="filters.outletCount" type="number" min="0" @change="apply"/></div><div class="field"><label>Última revisión desde</label><input v-model="filters.lastFrom" type="date" @change="apply"/></div><div class="field"><label>Orden</label><select v-model="filters.sort" @change="apply"><option value="accountNumber">Cuenta</option><option value="lastInspectionAt">Última revisión</option><option value="inspectionCount">Número de revisiones</option><option value="installationYear">Año</option><option value="flowLps">Gasto</option></select></div></section>
<div v-if="loading" class="skeleton loading"/><div v-else-if="error" class="error-box" role="alert">{{error}}</div><div v-else-if="!data?.items.length" class="empty-box">No hay hidrantes que coincidan con los filtros.</div>
<template v-else><div class="card table-wrap"><table><thead><tr><th>Cuenta</th><th>Información maestra</th><th>Coordenadas</th><th>Estado RV</th><th>Revisiones</th><th>Última revisión</th><th>Evidencia</th><th></th></tr></thead><tbody><tr v-for="h in data.items" :key="h.hydrantId"><td><RouterLink class="account mono" :to="`/hidrantes/${h.hydrantId}`">{{h.accountNumber}}</RouterLink></td><td>{{h.installationYear||'Año N/D'}} · {{h.flowLps!=null?`${h.flowLps} L/s`:'Gasto N/D'}}<small>{{h.outletCount!=null?`${h.outletCount} salidas`:'Salidas N/D'}}</small></td><td><span v-if="h.latitude!=null&&h.longitude!=null" class="coordinate"><MapPin :size="15"/>Disponibles</span><span v-else class="muted">Sin coordenadas</span></td><td><AppStatus :status="h.rvStatus"/></td><td>{{h.inspectionCount}}</td><td>{{date(h.lastInspectionAt)}}<small>{{h.latestTechnicianName||''}}</small></td><td>{{evidenceLabel(h)}}</td><td><RouterLink class="btn" :to="`/hidrantes/${h.hydrantId}`">Ver expediente</RouterLink></td></tr></tbody></table></div>
<div class="cards"><article v-for="h in data.items" :key="h.hydrantId" class="card hydrant-card"><header><RouterLink class="account mono" :to="`/hidrantes/${h.hydrantId}`">{{h.accountNumber}}</RouterLink><AppStatus :status="h.rvStatus"/></header><dl><div><dt>Revisiones</dt><dd>{{h.inspectionCount}}</dd></div><div><dt>Última</dt><dd>{{date(h.lastInspectionAt)}}</dd></div><div><dt>Maestro</dt><dd>{{h.installationYear||'Año N/D'}} · {{h.flowLps!=null?`${h.flowLps} L/s`:'Gasto N/D'}}</dd></div><div><dt>Evidencia</dt><dd>{{evidenceLabel(h)}}</dd></div></dl><RouterLink class="btn btn--primary" :to="`/hidrantes/${h.hydrantId}`">Ver expediente</RouterLink></article></div>
<footer class="pager"><span>{{(data.page-1)*data.pageSize+1}}–{{Math.min(data.page*data.pageSize,data.total)}} de {{data.total}}</span><select v-model="filters.pageSize" aria-label="Registros por página" @change="apply"><option :value="25">25</option><option :value="50">50</option><option :value="100">100</option></select><button class="btn" :disabled="data.page===1" @click="go(data.page-1)">Anterior</button><button class="btn" :disabled="data.page*data.pageSize>=data.total" @click="go(data.page+1)">Siguiente</button></footer></template></div></template>
<style scoped>.toolbar-card{padding:10px;display:flex;gap:9px;margin-bottom:12px}.search{height:42px;display:flex;align-items:center;gap:8px;border:1px solid #ccd6e2;border-radius:7px;padding:0 11px;flex:1}.search input{border:0;outline:0;width:100%}.filters{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;padding:14px;margin-bottom:12px}.loading{height:360px}.table-wrap{overflow:auto}table{border-collapse:collapse;width:100%;min-width:1120px}th,td{text-align:left;padding:12px;border-bottom:1px solid #e6ebf1;font-size:.8rem;vertical-align:middle}th{color:#61738b;background:#f8fafc;font-size:.7rem;text-transform:uppercase}td small{display:block;color:var(--muted);margin-top:4px}.account{font-weight:750;color:#1559cf;text-decoration:none}.coordinate{display:flex;align-items:center;gap:4px;color:#1763d4}.cards{display:none}.pager{display:flex;justify-content:flex-end;align-items:center;gap:9px;margin-top:14px;font-size:.8rem}.pager select{height:40px;border:1px solid #ccd6e2;border-radius:7px}.pager button:disabled{opacity:.45}.status--completed{color:#087a3b;background:#ebfaf2;border-color:#bcead0}.status--pending{color:#805800;background:#fff8e5;border-color:#ead99c}@media(max-width:1100px){.filters{grid-template-columns:repeat(2,1fr)}}@media(max-width:900px){.table-wrap{display:none}.cards{display:grid;grid-template-columns:repeat(2,1fr);gap:10px}.hydrant-card{padding:14px}.hydrant-card header{display:flex;justify-content:space-between;align-items:center}.hydrant-card dl{display:grid;grid-template-columns:1fr 1fr;gap:10px}.hydrant-card dt{font-size:.68rem;color:var(--muted)}.hydrant-card dd{font-size:.8rem;margin:3px 0}.pager{flex-wrap:wrap}}@media(max-width:560px){.toolbar-card{display:grid;grid-template-columns:1fr 1fr}.search{grid-column:1/-1}.filters,.cards{grid-template-columns:1fr}.pager{justify-content:center}.pager span{width:100%;text-align:center}}</style>
